### ISSUE TITLE
Asus AC68U with firmware 3.0.0.4.376_3626 is also vulnerable

### ISSUE THREAD

**Issue by Arie** [jduck/asus-cmd#5]
The AC68U with stock firmware is vulnerable. Firmware version: 3.0.0.4.376_3626-g9a8323e

**Comment by jduck** [comment]
Thanks. I'll update the README to reflect your report.

**Comment by rincebrain** [comment]
Also affects:
AC68U with 3.0.0.4.374_4561-g5f5c8d8
